apiVersion: v1

## NOTES
# Bikin ini mending pake command aja
# kubectl create secret docker-registry <nama-secret> \
#     --docker-email=tiger@acme.example \
#     --docker-username=tiger \
#     --docker-password=pass1234 \
#     --docker-server=my-registry.example:5000

kind: Secret
metadata:
  name: docker-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    Ini base 64 dari .docker/config.json
