apiVersion: v1
kind: Secret
metadata:
  name: ssh-secret

## NOTE: Mending pake command aja
# kubectl create secret tls my-tls-secret \
#    --cert=path/to/cert/file \
#    --key=path/to/key/file

# Ini kek Opaque cuma typenya buat penanda aja
type: kubernetes.io/tls

# Wajib ada tls.key sama tls.crt
stringData:
  tls.key: |
    MIIC2DCCAcCgAwIBAgIBATANBgkqh....
  tls.crt: |
    MIIEpgIBAAKCAQEA7yn3bRHQ5FHMQ ...
