apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world-job
spec:
  # Spek punya si job
  completions: 10
  parallelism: 20
  backoffLimit: 3
  # Klo dah 60 detik, langsung shutdown
  activeDeadlineSeconds: 60
  # Klo dah selesai, 30 detik hapus job ini
  ttlSecondsAfterFinished: 30
  template:
    metadata:
      name: hello-world-job
    spec:
      # Ini speknya si pod
      restartPolicy: OnFailure
      containers:
        - name: hello-world-container
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["echo 'Hello world'; sleep 8"]
